update the time zone convertor example
mahmoud/clastic pull request #40
Opened 2024-06-15 19:43 UTC by uyar

2024-06-15 21:08 UTC, mahmoud requested changes
Looks great! A marked improvement. A couple of suggestions, open to discussion. Thanks again for this!

2024-06-15 21:08 UTC, mahmoud commented on docs/tutorial.rst
> +As our next step, let us apply some style to our page.
```suggestion
As our next step, let us apply some style to our page.
Adding styles will require a CSS file, which should be served without processing.
Such files are generally known as *static assets*.
```
I feel like this explains the term "static" and the fact that it's a general term, not specific to Clastic.

2024-06-15 21:08 UTC, mahmoud commented on docs/tutorial.rst
> +By default, it contains dummy information:
```suggestion
By default, it contains placeholder values:
```

2024-06-15 21:13 UTC, uyar commented on docs/tutorial.rst
> +     in Tijuana and Timbuktu.
Tasmania is not in the Python builtin zoneinfo database.

2024-06-15 21:14 UTC, uyar commented on docs/tutorial.rst
> +It consists of a Python source file and an HTML template file,
That's fine.

2024-06-16 19:48 UTC, uyar commented on docs/tutorial.rst
> +It consists of a Python source file and an HTML template file,
Done.

2024-06-24 23:07 UTC, mahmoud commented
Looks great, thank you!

2024-06-24 23:07 UTC, merged